/**
 * 加载游戏中的资源
 */

var res = {
    //json文件
    failGameDialog_json : "res/failGameDialog.json",
    HelpDialog_json : "res/HelpDialog.json",
    MainScene_json : "res/MainScene.json",
    pauseDialog_json : "res/pauseDialog.json",
    progressHelp_json : "res/progressHelp.json",
    progressMenu_json : "res/progressMenu.json",
    progressTime_json : "res/progressTime.json",
    SceneMenu_json : "res/SceneMenu.json",
    settingDialog_json : "res/settingDialog.json",
    SettingMenu_json : "res/SettingMenu.json",
    successGameDialog_json : "res/successGameDialog.json",
    testNode_json : "res/testNode.json",

    //res文件夹下的图片
    bangzhu_png : "res/bangzhu.png",
    bangzhu1_png : "res/bangzhu1.png",
    bangzhu2_png : "res/bangzhu2.png",
    baoxiang_png : "res/baoxiang.png",
    beijingyinyue_png : "res/beijingyinyue.png",
    blackPoint_png : "res/blackPoint.png",
    brownPoint_png : "res/brownPoint.png",
    buttonHelp1_png : "res/buttonHelp1.png",
    buttonHelp2_png : "res/buttonHelp2.png",
    caidan1_png : "res/caidan1.png",
    caidan2_png : "res/caidan2.png",
    chongkai1_png : "res/chongkai1.png",
    chongkai2_png : "res/chongkai2.png",
    chongwan1_png : "res/chongwan1.png",
    chongwan2_png : "res/chongwan2.png",
    di_png : "res/di.png",
    di2_png : "res/di2.png",
    dianjigengduo1_png: "res/dianjigengduo1.png",
    dianjigengduo2_png : "res/dianjigengduo2.png",
    dianjishouhui1_png : "res/dianjishouhui1.png",
    dianjishouhui2_png : "res/dianjishouhui2.png",
    diduosg_png : "res/diduosg.png",
    fanhui1_png : "res/fanhui1.png",
    fanhui2_png : "res/fanhui2.png",
    gengduo1_png : "res/gengduo1.png",
    gengduo2_png : "res/gengduo2.png",
    guan1_png : "res/guan1.png",
    guan2_png : "res/guan2.png",
    HelloWorld_png : "res/HelloWorld.png",
    help0_png : "res/help0.png",
    help1_png : "res/help1.png",
    help2_png : "res/help2.png",
    help3_png : "res/help3.png",
    help4_png : "res/help4.png",
    help5_png : "res/help5.png",
    help6_png : "res/help6.png",
    help7_png : "res/help7.png",
    jindu_png : "res/jindu.png",
    jindu2_png : "res/jindu2.png",
    jixu1_png : "res/jixu1.png",
    jixu2_png : "res/jixu2.png",
    ku_png : "res/ku.png",
    kuang_png : "res/kuang.png",
    kuang1_png : "res/kuang1.png",
    kuang3_png : "res/kuang3.png",
    menu_sound_off_png : "res/menu_sound_off.png",
    menu_sound_on_png : "res/menu_sound_on.png",
    now_score_png : "res/now_score.png",
    now_score_aim_png : "res/now_score_aim.png",
    qian_png : "res/qian.png",
    sb_png : "res/sb.png",
    shang_png : "res/shang.png",
    shezhi_png : "res/shezhi.png",
    shezhi1_png : "res/shezhi1.png",
    shezhi2_png : "res/shezhi2.png",
    shibai_png : "res/shibai.png",
    shijiankuang_png : "res/shijiankuang.png",
    shijianshuzi_png : "res/shijianshuzi.png",
    sl_png : "res/sl.png",
    tanchu2_png : "res/tanchu2.png",
    tu0_png : "res/tu0.png",
    tuichu1_png : "res/tuichu1.png",
    tuichu2_png : "res/tuichu2.png",
    wjx1_png : "res/wjx1.png",
    xiangyou1_png : "res/xiangyou1.png",
    xiangyou2_png : "res/xiangyou2.png",
    xiangzuo1_png : "res/xiangzuo1.png",
    xiangzuo2_png : "res/xiangzuo2.png",
    xiayiguan1_png : "res/xiayiguan1.png",
    xiayiguan2_png : "res/xiayiguan2.png",
    xuanguanbeijing_png : "res/xuanguanbeijing.png",
    yinxiao_png : "res/yinxiao.png",
    you_png : "res/you.png",
    you1_png : "res/you1.png",
    zuo_png : "res/zuo.png",
    zuo1_png : "res/zuo1.png",
    defaultBMFont_png : "res/defaultBMFont.png",
    defaultBMFont_fnt : "res/defaultBMFont.fnt",

    //SceneStart文件夹下的图片
    bangzhu1_png : "res/SceneStart/bangzhu1.png",
    bangzhu2_png : "res/SceneStart/bangzhu2.png",
    beijing_png : "res/SceneStart/beijing.png",
    dianjigengduo1_png : "res/SceneStart/dianjigengduo1.png",
    dianjigengduo2_png : "res/SceneStart/dianjigengduo2.png",
    dianjijixu_png : "res/SceneStart/dianjijixu.png",
    dianjishouhui1_png : "res/SceneStart/dianjishouhui1.png",
    dianjishouhui2_png : "res/SceneStart/dianjishouhui2.png",
    gengduo1_png: "res/SceneStart/gengduo1.png",
    gengduo2_png : "res/SceneStart/gengduo2.png",
    guaiwuwo1_png : "res/SceneStart/guaiwuwo1.png",
    guaiwuwo2_png : "res/SceneStart/guaiwuwo2.png",
    guan1_png : "res/SceneStart/guan1.png",
    guan2_png : "res/SceneStart/guan2.png",
    guanyu1_png : "res/SceneStart/guanyu1.png",
    guanyu2_png : "res/SceneStart/guanyu2.png",
    juqing1_png : "res/SceneStart/juqing1.png",
    juqing2_png : "res/SceneStart/juqing2.png",
    kaishi1_png : "res/SceneStart/kaishi1.png",
    kaishi2_png : "res/SceneStart/kaishi2.png",
    kuang2_png : "res/SceneStart/kuang2.png",
    logo_png : "res/SceneStart/logo.png",
    paihangbang1_png : "res/SceneStart/paihangbang1.png",
    paihangbang2_png : "res/SceneStart/paihangbang2.png",
    pinkPoint_png : "res/SceneStart/pinkPoint.png",
    shangcheng1_png : "res/SceneStart/shangcheng1.png",
    shangcheng2_png : "res/SceneStart/shangcheng2.png",
    shezhi1_png : "res/SceneStart/shezhi1.png",
    shezhi2_png : "res/SceneStart/shezhi2.png",
    sunwukong_png : "res/SceneStart/sunwukong.png",
    tanchu_png : "res/SceneStart/tanchu.png",
    tanchu2_png : "res/SceneStart/tanchu2.png",
    tangseng_png : "res/SceneStart/tangseng.png",
    tangseng1_png : "res/SceneStart/tangseng1.png",
    tangseng2_png : "res/SceneStart/tangseng2.png",
    tangseng3_png : "res/SceneStart/tangseng3.png",
    tangseng4_pn : "res/SceneStart/tangseng4.png",
    tangseng5_png : "res/SceneStart/tangseng5.png",
    tangseng6_png : "res/SceneStart/tangseng6.png",
    tiaozhan1_png : "res/SceneStart/tiaozhan1.png",
    tiaozhan2_png : "res/SceneStart/tiaozhan2.png",
    tuichu1_png : "res/SceneStart/tuichu1.png",
    tuichu2_png : "res/SceneStart/tuichu2.png",
    xiaolongnv0_png : "res/SceneStart/xiaolongnv0.png",
    xiaolongnv1_png : "res/SceneStart/xiaolongnv1.png",
    xiaolongnv2_png : "res/SceneStart/xiaolongnv2.png",
    xiaolongnv3_png : "res/SceneStart/xiaolongnv3.png",
    xiaolongnv4_png : "res/SceneStart/xiaolongnv4.png",
    xiaolongnv5_png : "res/SceneStart/xiaolongnv5.png",
    xiaolongnv6_png : "res/SceneStart/xiaolongnv6.png",
    yanjing1_png : "res/SceneStart/yanjing1.png",
    yanjing2_png : "res/SceneStart/yanjing2.png",
    yun_png : "res/SceneStart/yun.png",
    yun01_png : "res/SceneStart/yun01.png",
    yun02_png : "res/SceneStart/yun02.png",
    yun03_png : "res/SceneStart/yun03.png",
    zhalan_png : "res/SceneStart/zhalan.png",
    zhubajie_png : "res/SceneStart/zhubajie.png",
    zuanshi_png : "res/SceneStart/zuanshi.png",

    //SceneMenu文件夹下的图片
    huoyanshan_png : "res/SceneMenu/huoyanshan.png",
    lingshan_png : "res/SceneMenu/lingshan.png",
    nverguo_png : "res/SceneMenu/nverguo.png",
    tongtianhe_png : "res/SceneMenu/tongtianhe.png",
    tu0_png : "res/SceneMenu/tu0.png",
    tu1_png : "res/SceneMenu/tu1.png",
    tu2_png : "res/SceneMenu/tu2.png",
    tu3_png : "res/SceneMenu/tu3.png",
    tu4_png : "res/SceneMenu/tu4.png",
    yellowPoint_png : "res/SceneMenu/yellowPoint.png",

    //SceneGame文件夹下的图片
    add_png : "res/SceneGame/add.png",
    bajie_png : "res/SceneGame/bajie.png",
    daojushuzi_png : "res/SceneGame/daojushuzi.png",
    gouzi_png : "res/SceneGame/gouzi.png",
    gunlun_png : "res/SceneGame/gunlun.png",
    haigui_png : "res/SceneGame/haigui.png",
    huolianhua_png : "res/SceneGame/huolianhua.png",
    masking_png : "res/SceneGame/masking.png",
    shaseng_png : "res/SceneGame/shaseng.png",
    shengzi_png : "res/SceneGame/shengzi.png",
    start_png : "res/SceneGame/start.png",
    start1_png : "res/SceneGame/start1.png",
    start2_png : "res/SceneGame/start2.png",
    start3_png : "res/SceneGame/start3.png",
    tangseng_png : "res/SceneGame/tangseng.png",
    wukong_png : "res/SceneGame/wukong.png",
    xiaolongnv_png : "res/SceneGame/xiaolongnv.png",
    yun1_png : "res/SceneGame/yun1.png",
    yun3_png : "res/SceneGame/yun3.png",
    zanting1_png : "res/SceneGame/zanting1.png",
    zanting2_png : "res/SceneGame/zanting2.png",

    //SceneGame文件夹下的plist文件
    bajie_plist : "res/SceneGame/bajie.plist",
    haigui_plist : "res/SceneGame/haigui.plist",
    huolianhua_plist : "res/SceneGame/huolianhua.plist",
    shaseng_plist : "res/SceneGame/shaseng.plist",
    tangseng_plist : "res/SceneGame/tangseng.plist",
    wukong_plist : "res/SceneGame/wukong.plist",
    xiaolongnv_plist : "res/SceneGame/xiaolongnv.plist",

    //tmx文件夹下的tmx文件
    baoxiangguo1_tmx : "res/tmx/baoxiangguo1.tmx",
    baoxiangguo10_tmx : "res/tmx/baoxiangguo10.tmx",
    baoxiangguo11_tmx : "res/tmx/baoxiangguo11.tmx",
    baoxiangguo12_tmx : "res/tmx/baoxiangguo12.tmx",
    baoxiangguo2_tmx : "res/tmx/baoxiangguo2.tmx",
    baoxiangguo3_tmx : "res/tmx/baoxiangguo3.tmx",
    baoxiangguo4_tmx : "res/tmx/baoxiangguo4.tmx",
    baoxiangguo5_tmx : "res/tmx/baoxiangguo5.tmx",
    baoxiangguo6_tmx : "res/tmx/baoxiangguo6.tmx",
    baoxiangguo7_tmx: "res/tmx/baoxiangguo7.tmx",
    baoxiangguo8_tmx : "res/tmx/baoxiangguo8.tmx",
    baoxiangguo9_tmx : "res/tmx/baoxiangguo9.tmx",
    huoyanshan1_tmx : "res/tmx/huoyanshan1.tmx",
    huoyanshan10_tmx : "res/tmx/huoyanshan10.tmx",
    huoyanshan11_tmx : "res/tmx/huoyanshan11.tmx",
    huoyanshan12_tmx : "res/tmx/huoyanshan12.tmx",
    huoyanshan2_tmx : "res/tmx/huoyanshan2.tmx",
    huoyanshan3_tmx : "res/tmx/huoyanshan3.tmx",
    huoyanshan4_tmx : "res/tmx/huoyanshan4.tmx",
    huoyanshan5_tmx : "res/tmx/huoyanshan5.tmx",
    huoyanshan6_tmx : "res/tmx/huoyanshan6.tmx",
    huoyanshan7_tmx : "res/tmx/huoyanshan7.tmx",
    huoyanshan8_tmx : "res/tmx/huoyanshan8.tmx",
    huoyanshan9_tmx : "res/tmx/huoyanshan9.tmx",
    lingshan1_tmx : "res/tmx/lingshan1.tmx",
    lingshan10_tmx : "res/tmx/lingshan10.tmx",
    lingshan2_tmx : "res/tmx/lingshan2.tmx",
    lingshan3_tmx : "res/tmx/lingshan3.tmx",
    lingshan4_tmx : "res/tmx/lingshan4.tmx",
    lingshan5_tmx : "res/tmx/lingshan5.tmx",
    lingshan6_tmx : "res/tmx/lingshan6.tmx",
    lingshan7_tmx : "res/tmx/lingshan7.tmx",
    lingshan8_tmx : "res/tmx/lingshan8.tmx",
    lingshan9_tmx : "res/tmx/lingshan9.tmx",
    nverguo1_tmx : "res/tmx/nverguo1.tmx",
    nverguo10_tmx : "res/tmx/nverguo10.tmx",
    nverguo11_tmx : "res/tmx/nverguo11.tmx",
    nverguo2_tmx : "res/tmx/nverguo2.tmx",
    nverguo3_tmx : "res/tmx/nverguo3.tmx",
    nverguo4_tmx : "res/tmx/nverguo4.tmx",
    nverguo5_tmx : "res/tmx/nverguo5.tmx",
    nverguo6_tmx : "res/tmx/nverguo6.tmx",
    nverguo7_tmx : "res/tmx/nverguo7.tmx",
    nverguo8_tmx : "res/tmx/nverguo8.tmx",
    nverguo9_tmx : "res/tmx/nverguo9.tmx",
    tongtianhe1_tmx : "res/tmx/tongtianhe1.tmx",
    tongtianhe10_tmx : "res/tmx/tongtianhe10.tmx",
    tongtianhe11_tmx : "res/tmx/tongtianhe11.tmx",
    tongtianhe2_tmx : "res/tmx/tongtianhe2.tmx",
    tongtianhe3_tmx : "res/tmx/tongtianhe3.tmx",
    tongtianhe4_tmx : "res/tmx/tongtianhe4.tmx",
    tongtianhe5_tmx : "res/tmx/tongtianhe5.tmx",
    tongtianhe6_tmx : "res/tmx/tongtianhe6.tmx",
    tongtianhe7_tmx : "res/tmx/tongtianhe7.tmx",
    tongtianhe8_tmx : "res/tmx/tongtianhe8.tmx",
    tongtianhe9_tmx : "res/tmx/tongtianhe9.tmx",

    //tmx文件夹下的图片
    bg01_png : "res/tmx/bg01.png",
    bg02_png : "res/tmx/bg02.png",
    bg03_png : "res/tmx/bg03.png",
    bg04_png : "res/tmx/bg04.png",
    bg05_png : "res/tmx/bg05.png",
    goods_026_png : "res/tmx/goods_026.png",
    goods_1_png : "res/tmx/goods_1.png",
    goods_10_png : "res/tmx/goods_10.png",
    goods_11_png : "res/tmx/goods_11.png",
    goods_12_png : "res/tmx/goods_12.png",
    goods_13_png : "res/tmx/goods_13.png",
    goods_14_png : "res/tmx/goods_14.png",
    goods_15_png : "res/tmx/goods_15.png",
    goods_16_png : "res/tmx/goods_16.png",
    goods_17_png : "res/tmx/goods_17.png",
    goods_2_png : "res/tmx/goods_2.png",
    goods_3_png : "res/tmx/goods_3.png",
    goods_4_png : "res/tmx/goods_4.png",
    goods_5_png : "res/tmx/goods_5.png",
    goods_6_png : "res/tmx/goods_6.png",
    goods_7_png : "res/tmx/goods_7.png",
    goods_8_png : "res/tmx/goods_8.png",
    goods_9_png : "res/tmx/goods_9.png",

    //texiao文件夹下的粒子特效
    yezi2_plist : "res/texiao/yezi/yezi2.plist",
    xuehua_plist : "res/texiao/xuehua/xuehua.plist",
    yanhua_plist : "res/texiao/yanhua/yanhua.plist",
    paopao_plist : "res/texiao/paopao/paopao.plist",
    shouye_plist : "res/texiao/shouye/shouye.plist",

    //音乐文件
    sound001_mp3 : "res/music/sound001.mp3",
    sound002_mp3 : "res/music/sound002.mp3",
    sound003_mp3 : "res/music/sound003.mp3",
    sound004_mp3 : "res/music/sound004.mp3",
    sound005_mp3 : "res/music/sound005.mp3",
    sound006_mp3 : "res/music/sound006.mp3",
    sound007_mp3 : "res/music/sound007.mp3",
    sound008_mp3 : "res/music/sound008.mp3",
    sound010_mp3 : "res/music/sound010.mp3",
    sound014_mp3 : "res/music/sound014.mp3",
    sound015_mp3 : "res/music/sound015.mp3",
    sound017_mp3 : "res/music/sound017.mp3",
    sound018_mp3 : "res/music/sound018.mp3",
    sound029_mp3 : "res/music/sound029.mp3",
    sound030_mp3 : "res/music/sound030.mp3",
    sound082_mp3 : "res/music/sound082.mp3",
    sound083_mp3 : "res/music/sound083.mp3",
    sound_bomb_mp3 : "res/music/sound_bomb.mp3"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
